---
pipeline:
  lint-shell:
    image: sevoid/linter:latest
    pull: true
    commands:
      - ./.ci/lint-shell.sh
    group: lint
    when:
      event:
        - push
      branch:
        exclude:
          - master
          - release-*
          - archive/*

  lint-yaml:
    image: sevoid/linter:latest
    pull: true
    commands:
      - ./.ci/lint-yaml.sh
    group: lint
    when:
      event:
        - push
      branch:
        exclude:
          - master
          - release-*
          - archive/*

  lint-python:
    image: sevoid/linter:latest
    pull: true
    commands:
      - sudo pip install -q -r ./.ci/pylint_requirements.txt -e .
      - ./.ci/lint_python.py || exit 0
    group: lint
    when:
      event:
        - push
      branch:
        exclude:
          - master
          - release-*
          - archive/*

  test-unittest:
    image: python:3-alpine
    pull: true
    commands:
      - apk add -q --no-cache build-base openssl openssl-dev libffi libffi-dev sqlite
      - pip install -q -r requirements.txt -e .
      - python -m unittest discover -s tests -p "test_*.py"
    group: test
    when:
      event:
        - push
      branch:
        exclude:
          - master
          - release-*
          - archive/*

  publish-dev:
    image: plugins/docker:17
    pull: true
    secrets:
      - docker_username
      - docker_password
    repo: sevoid/cryptopotato-bot
    group: build
    tags:
      - dev-${DRONE_COMMIT:0:7}
    when:
      event:
        - push
      branch:
        - dev-*
        - feature-*
        - feature/*

  publish-release:
    image: plugins/docker:17
    pull: true
    secrets:
      - docker_username
      - docker_password
    repo: sevoid/cryptopotato-bot
    group: build
    tags:
      - latest
      - ${DRONE_TAG}
    when:
      branch:
        - master
        - release-*
      event:
        - push
        - tag

# vim:set syntax=yaml ts=2 sw=2 et:
